enyo.depends(
	"Palette.js",
	"Palette.css",
	"Json.js",
	"Serializer.js",
	"Inspector.css",
	"Inspector.js",
	"ComponentView.js",
	"InspectorConfig.js",
	"Sandbox.js",
	"IFrameDesigner.js",
	"designer.css",
	"RPCCommunicator.js"
);
