enyo.depends(
	"ServiceRegistry.js",
	"FileSystemService.js",
	"HermesNode.js",
	"HermesFileSystem.js",
	"HermesFileTree.js",
	"ProjectProperties.js",
	"phonegap/ProjectProperties.js",
	"phonegap/PhonegapUIRows.js",
	"phonegap/Build.js",
	"GenZip.js",
	"phonegap/BuildStatusUI.js"
);
