enyo.depends(
	"ServiceRegistry.js",
	"FileSystemService.js",
	"Node.js",
	"HermesFileSystem.js",
	"HermesFileTree.js",
	"phonegap/ProjectProperties.js",
	"phonegap/Build.js",
	"ProjectToolkit.js"
);
