enyo.depends(
	"../assets/css/AresNode.css",
	"../assets/css/HermesFileTree.css",
	"ServiceRegistry.js",
	"FileSystemService.js",
	"AresNode.js",
	"HermesFileSystem.js",
	"HermesFileTree.js",
	"ProjectProperties.js",
	"phonegap/ProjectProperties.js",
	"phonegap/Build.js",
	"GenZip.js"
);
