enyo.depends(
	"$lib/layout",
	"$lib/onyx",
	"$lib/foss",
	"source/",
	"Ares.css",
	//
	"$lib/extra/analyzer2",
	"../utilities/source",
	"../phobos/source",
	//
	"../deimos/source",
	"../deimos/resources",
	//
	"../lib/localStorage",
	"../lib/service",
	"../harmonia/source",
	"../project-view/source"
);
