enyo.depends(
	"$lib/g11n",
	"$lib/layout",
	"$lib/onyx",
	"$lib/foss",
	"source/",
	"Ares.css",
	"../model/source",
	"$lib/extra/analyzer2",
	"../utilities/source",
	"../services/source",
	"../phobos/source",
	"../deimos/source",
	"../deimos/resources",
	"../harmonia/source",
	"../project-view/source"
);
