enyo.depends(
	"FieldDecorator.js",
	"DropboxAuthConfig.js",
	"ProviderList.js",
	"Harmonia.js",
	"NamePopup.js",
	"DeletePopup.js",
	"RenamePopup.js",
	"AccountsConfigurator.js",
	"BasicAuthConfig.js"
);
