enyo.depends(
	"ServiceRegistry.js",
	"FileSystemService.js",
	"HermesFileSystem.js",
	"ProjectProperties.js",
	"phonegap/PhonegapUiData.js",
	"phonegap/ProjectProperties.js",
	"phonegap/BuildStatusUI.js",
	"phonegap/PhonegapUIRows.js",
	"phonegap/Build.js",
	"phonegap/QrCode.js",
	"GenZip.js"	
);
