enyo.depends(
	"lang.js",
	"Groupbox.js",
	"ActionPopup.js",
	"ErrorPopup.js",
	"AsyncError.js",
	"IFrame.js",
	"LocalStorage.js",
	"FileChooser.js",
	"LinkController.js",
	"PanelGrabber.js",
	"Popup.js" 
);
