enyo.depends(
	"Ares.js",
	"DocumentToolbar.js",
	"FileData.js",
	"WorkspaceData.js",
	"PackageMunger.js",
	"EnyoEditor.js",
	"utilities",
	"services",
	"enyo-editor",
	"harmonia",
	"project-view"
);
